#---------------------------------#
#  Build Script                   #
#---------------------------------#

build_script:
  - ps: .\build.ps1 -Target AppVeyor

#---------------------------------#
# Tests
#---------------------------------#

test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Transifex                      #
#---------------------------------#
init:
- ps: |
    $encoding = New-Object System.Text.UTF8Encoding($false)
    $text = "[https://www.transifex.com]`r`nhostname = https://www.transifex.com`r`npassword = $env:TRANSIFEX_TOKEN`r`nusername = api"
    [System.IO.File]::WriteAllText("$env:USERPROFILE\.transifexrc", $text, $encoding)
    if (!(Test-Path $env:TRANSLATION_DIR)) { mkdir $env:TRANSLATION_DIR }
install:
- cmd: pip install transifex-client

#---------------------------------#
#  Build Cache                    #
#---------------------------------#

cache:
- '%TRANSLATION_DIR%'
- Source\packages -> Source\**\packages.config
- tools -> setup.cake
