#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target AppVeyor

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/    

#---------------------------------#
#  notifications configuration    #
#---------------------------------#
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/4933c447ea42a0480587
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
   
#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\BuildScripts\build.ps1
  
test: off

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Source\packages -> Source\**\packages.config
- Tools -> build.ps1

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /\(doc\).*/